modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "classic_obsidian"
version = "${version}"
displayName = "Classic Obsidian Tools"
authors = "satyrnidae"
description = '''
Adds unbreakable obsidian tools that work at the same level as stone!
'''
logoFile = "icon.png"

[[dependencies.classic_obsidian]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.classic_obsidian]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.classic_obsidian]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
